### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by llTheBlankll** [saitamasahil/Pixel-Launcher-Extended#16]
```
time: 1670915121879
device fp:google/cheetah/cheetah:13/TD1A.221105.003/9229241:user/release-keys
ricedroid ver:8.6
msg: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
stacktrace: android.view.InflateException: Binary XML file line #35 in com.google.android.apps.nexuslauncher:layout/search_edu_card: Binary XML file line #35 in com.google.android.apps.nexuslauncher:layout/search_edu_card: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #35 in com.google.android.apps.nexuslauncher:layout/search_edu_card: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.google.android.apps.nexuslauncher.allapps.d.onCreateViewHolder(Unknown Source:9)
	at com.android.launcher3.allapps.BaseAllAppsAdapter.onCreateViewHolder(SourceFile:3)
	at com.android.launcher3.allapps.BaseAllAppsAdapter.onCreateViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.j0.createViewHolder(Unknown Source:5)
	at androidx.recyclerview.widget.G0.I(Unknown Source:207)
	at androidx.recyclerview.widget.G0.p(Unknown Source:5)
	at androidx.recyclerview.widget.G0.o(Unknown Source:1)
	at androidx.recyclerview.widget.Q.d(Unknown Source:11)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(Unknown Source:95)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:38)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:356)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(Unknown Source:9)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:67)
	at android.view.View.measure(View.java:26373)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
	at android.view.View.measure(View.java:26373)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3834)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2566)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2282)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8957)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7901)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1105)
	at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:981)
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1060)
	at android.content.res.Resources.loadColorStateList(Resources.java:1148)
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:604)
	at android.widget.TextView.readTextAppearance(TextView.java:4124)
	at android.widget.TextView.<init>(TextView.java:1166)
	at android.widget.TextView.<init>(TextView.java:1067)
````

And one more
```
time: 1670916016291
device fp:google/cheetah/cheetah:13/TD1A.221105.003/9229241:user/release-keys
ricedroid ver:8.6
msg: java.lang.IllegalArgumentException: com.google.android.apps.wallpaper: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
stacktrace: java.lang.RuntimeException: Unable to create service com.google.android.apps.wallpaper.backdrop.BackdropRotationTask: java.lang.IllegalArgumentException: com.google.android.apps.wallpaper: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4528)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7901)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.IllegalArgumentException: com.google.android.apps.wallpaper: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
	at com.google.android.gms.gcm.GcmNetworkManager.<init>(GcmNetworkManager.java:24)
	at com.google.android.gms.gcm.GcmTaskService.onCreate(GcmTaskService.java:16)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4515)

```
Information:
Device: **Redmi Note 8 Pro (Begonia)**
GApps: **BitGApps Android 13**
ROM: RiceDroid 8.6 Vanilla November update

I selected Nov security update during the installation of Pixel Launcher

**How to reproduce?**
1. Swipe up and go to App Drawer.
2. Click the search box at the top.
3. Screen turns black and blink's about two times.
4. Crashes and will automatically come back as if nothing happened.
5. Repeat.

I just flashed my ROM recently so there should be no problem but somehow there is.

**Comment by saitamasahil** [comment]
Ricedroid has many conflicts with this launcher. You can fix some issues by visiting troubleshooting section. I recommend you to use some good gapps custom roms.
