### ISSUE TITLE
Crash when opening Wallpapers and Style

### ISSUE THREAD

**Issue by gsarris** [saitamasahil/Pixel-Launcher-Extended#39]
Hi @saitamasahil :) Thx for your work!

I am experiencing the following crash when trying to access Wallpapers & Style.

`FATAL EXCEPTION: main
Process: com.google.android.apps.wallpaper, PID: 25500
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.apps.wallpaper/com.android.wallpaper.picker.CustomizationPickerActivity}: android.view.InflateException: Binary XML file line #29 in com.google.android.apps.wallpaper:layout/activity_customization_picker: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.view.InflateException: Binary XML file line #29 in com.google.android.apps.wallpaper:layout/activity_customization_picker: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
Caused by: android.view.InflateException: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1237)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:469)
	at android.app.Activity.setContentView(Activity.java:3601)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:2)
	at com.android.wallpaper.picker.CustomizationPickerActivity.onCreate(CustomizationPickerActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.res.Resources$NotFoundException: File res/color/bottom_action_button_color_tint.xml from ComplexColor resource ID #0x7f060024
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1155)
	at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:981)
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1060)
	at android.content.res.Resources.getColorStateList(Resources.java:1139)
	at android.content.Context.getColorStateList(Context.java:826)
	at com.android.wallpaper.widget.BottomActionBar.setColor(BottomActionBar.java:61)
	at com.android.wallpaper.widget.BottomActionBar.<init>(BottomActionBar.java:215)
	... 30 more
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1, theme={InheritanceMap=[id=0x7f130123com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, id=0x7f130122com.google.android.apps.wallpaper:style/CustomizationTheme, id=0x1030223android:style/Theme.DeviceDefault.Settings, id=0x1030128android:style/Theme.DeviceDefault, id=0x1030403android:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getColor(TypedArray.java:535)
	at android.content.res.ColorStateList.inflate(ColorStateList.java:366)
	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:296)
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1148)
	... 36 more`

Poco X3 NFC, lineageOS 20

Magisk module that might conflict (latest pixelfy). I tried both Pixel and Aosp pickers.

Let me know if you need more logs :)

Thx in advance!

**Comment by saitamasahil** [comment]
Show modules list. Use official magisk only.. if u r using official then tell version details.

**Comment by gsarris** [comment]
![Screenshot_20230428-153318_Settings](https://user-images.githubusercontent.com/11834810/235191696-104bd7b9-1665-411e-894a-37d2371e5786.png)
![Screenshot_20230428-153329_Settings](https://user-images.githubusercontent.com/11834810/235191714-d632b290-aaa7-4005-9c17-2b45bd8827fc.png)

Thx for the reply. Here is the list.

I am using magisk 26.1 official 🙂

**Comment by waterblock79** [comment]
Disable the Pixel / AOSP wallpaper app may fix this problem (at least it works on my devices :D

**Comment by gsarris** [comment]
Hmm I can't find pixel or aosp wallpaper app in order to disable.

This means that module didn't install any of the 2?

**Comment by waterblock79** [comment]
It is a system application, so have u tried "Show system" option? :p

**Comment by Fede2782** [comment]
Same issue with May security and QPR2

**Comment by gsarris** [comment]
Hi! Sorry for the late reply. I did an clean flash on my phone for another reason. New install works as expected. No crashing.
