### ISSUE TITLE
Crash on Pixel 7 Pro qpr3 with PLE 1.7 beta after tapping Screenshot button in Recents (multitasking)

### ISSUE THREAD

**Issue by nokia5700black** [saitamasahil/Pixel-Launcher-Extended#56]
![photo_2023-06-15_19-09-19](https://github.com/saitamasahil/Pixel-Launcher-Extended/assets/3038241/ab3331ac-b09f-48cd-b009-19254fbeb5c7)

Process: com.google.android.apps.nexuslauncher
PID: 3319
UID: 10221
Frozen: false
Flags: 0x34cbbe45
Package: com.google.android.apps.nexuslauncher v906 (13)
Foreground: Yes
Process-Runtime: 13228
Build: google/cheetah/cheetah:13/TQ3A.230605.012/10204971:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/util/ScreenshotHelper$HardwareBitmapBundler;
 at com.android.quickstep.util.ImageActionUtils.saveScreenshot(Unknown Source:0)
 at com.android.quickstep.fallback.a.run(Unknown Source:255)
 at com.android.quickstep.views.RecentsView.lambda$finishRecentsAnimation$37(Unknown Source:2)
 at com.android.quickstep.views.RecentsView.B(Unknown Source:0)
 at P.a.run(Unknown Source:479)
 at com.android.launcher3.util.RunnableList.executeAllAndClear(Unknown Source:20)
 at com.android.launcher3.util.RunnableList.executeAllAndDestroy(Unknown Source:3)
 at com.android.launcher3.h.run(Unknown Source:7)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7918)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassNotFoundException: com.android.internal.util.ScreenshotHelper$HardwareBitmapBundler
 ... 16 more

```

**Comment by nokia5700black** [comment]
fixed in beta (13.08.23)

thx!

![Screenshot_20230813-182251](https://github.com/saitamasahil/Pixel-Launcher-Extended/assets/3038241/12334cc2-2883-4988-8b88-7cdd12f2239e)
