### ISSUE TITLE
Pixel Launcher Extended keeps crushing after instalation [BUG]

### ISSUE THREAD

**Issue by mchyla7** [saitamasahil/Pixel-Launcher-Extended#71]
Version - 1.7
Magisk - 26.1
Android 13 QPR3

I just tried to install the module on my phone (without any settings customized on manual install), and after rebooting the device, Launcher can't turn on and crashes.

config.txt
`1. LAUNCHER=03
 2. DT2S=0
 3. Pixel_Launcher_Mods_App=0
 4. Icon_Shape_Changer_App=0
 5. #Don't modify anything after this`

[log](https://bin.kv2.dev/~64ed0c305de7ed6bfdb8eba5)
`
time: 1693257558061
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:266)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6706)
at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7927)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
`

**Comment by DrKoneko** [comment]
Bump. Having the same issue unfortunately.  I'm on a google Pixel 6 pro

**Comment by jeffdumcum** [comment]
Same issue on Pixel Tablet
