### ISSUE TITLE
Keeps crashing 

### ISSUE THREAD

**Issue by spiral009** [saitamasahil/Pixel-Launcher-Extended#76]
I followed the instructions set
Launch=22 
No double taps 
When rebooted i get a black screen and pixel extended keeps on crashing i opened the settings via notification bar and downloaded a launcher from Google play for now
I do have iconfiy, disabling it didn't fix it
```
================================================================
    Generated by AppErrorsTracking
    Project Url: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: realme
[Device Model]: RMX3370
[Display]: TQ2A.230505.002.A1
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ar_IQ
[Process ID]: 8821
[CPU ABI]: none
[Package Name]: com.google.android.apps.nexuslauncher
[Version Name]: 13
[Version Code]: 906
[Error Type]: JVM
[Crash Time]: 2023-10-17T02:04:15.239
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:270)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6682)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by soaska** [comment]
My crashes when im trying to copy browser link

**Comment by soaska** [comment]
```
time: 1698437754453
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.prediction.AppPredictor android.app.prediction.AppPredictionManager.createAppPredictionSession(android.app.prediction.AppPredictionContext)' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.prediction.AppPredictor android.app.prediction.AppPredictionManager.createAppPredictionSession(android.app.prediction.AppPredictionContext)' on a null object reference
	at androidx.appcompat.widget.SearchView$PreQAutoCompleteTextViewReflector.a(Unknown Source:53)
	at p1.g.f(Unknown Source:33)
	at O.a.run(Unknown Source:66)
	at com.android.quickstep.views.RecentsView.lambda$finishRecentsAnimation$39(Unknown Source:2)
	at com.android.quickstep.views.RecentsView.T(Unknown Source:0)
	at com.android.quickstep.views.B.run(Unknown Source:62)
	at com.android.launcher3.util.RunnableList.executeAllAndClear(Unknown Source:20)
	at com.android.launcher3.util.RunnableList.executeAllAndDestroy(Unknown Source:3)
	at com.android.quickstep.n0.run(Unknown Source:82)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

``` /
